version: '2'

services:
  front_builder:
    build: ./front/
    restart: "no"
    volumes:
      - ./front:/app
    command: npm run build
  back:
    build: ./back/
    command: go run .
    volumes:
      - ./back:/go/src/app
  nginx:
    image: nginx
    volumes:
      - ./front/src:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
      - 9090:90